"""Generic templated-config-file lifecycle: render -> write (same-dir temp +
rename, so SELinux labels inherit and the write is atomic) -> back up the
previous content -> validate -> apply -> roll back on failure (PLAN.md §2).
Every NAS-OS-owned config file (Samba's nasos.conf, NFS's nasos.exports,
vsftpd.conf, ...) goes through one `ManagedFile` so the render/validate/
rollback contract is identical everywhere; only `render`/`validate`/`apply`
differ per service.
"""

from __future__ import annotations

import contextlib
import hashlib
import logging
import os
import shutil
import time
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from pathlib import Path

from nasos import __version__
from nasos.system.runner import Runner

logger = logging.getLogger(__name__)

DEFAULT_BACKUP_DIR = "/var/lib/nasos/config-backups"
MAX_BACKUPS = 20

HEADER_TEMPLATE = (
    "# Generated by NAS-OS {version} at {timestamp}. DO NOT EDIT; "
    "local overrides go in {owner_file}\n"
)


class ConfigValidationError(Exception):
    """`detail` is the validating tool's stderr, shown verbatim in the UI."""

    def __init__(self, detail: str) -> None:
        super().__init__(detail)
        self.detail = detail


class ConfigApplyError(Exception):
    def __init__(self, detail: str) -> None:
        super().__init__(detail)
        self.detail = detail


def render_header(*, owner_file: str) -> str:
    return HEADER_TEMPLATE.format(
        version=__version__,
        timestamp=time.strftime("%Y-%m-%d %H:%M:%S %z"),
        owner_file=owner_file,
    )


ValidateFn = Callable[[Path], Awaitable[None]]  # raises ConfigValidationError
ApplyFn = Callable[[], Awaitable[None]]  # raises ConfigApplyError


@dataclass
class ManagedFile:
    """One NAS-OS-owned config file.

    `render()` must return content that already includes the DO-NOT-EDIT
    header (see `render_header`) — this class doesn't add one, since where
    it goes (top of file vs. a marker block) is renderer-specific.
    `owner_file` is only used by callers composing error messages; this
    class doesn't reference it directly.
    """

    path: str
    render: Callable[[], str]
    runner: Runner
    validate: ValidateFn | None = None
    apply: ApplyFn | None = None
    mode: int = 0o644
    owner: str | None = None
    group: str | None = None
    backup_dir: str = DEFAULT_BACKUP_DIR

    async def write_and_apply(self) -> str:
        """Render, write, validate, apply — rolling back to the previous
        content on any failure. Returns the sha256 of the content left on
        disk (which is the new content on success, the restored previous
        content if validate/apply raised).
        """
        target = Path(self.path)
        previous = target.read_bytes() if target.exists() else None

        content = self.render()
        await self._write_atomic(target, content.encode())
        if previous is not None:
            self._backup(target, previous)

        if self.validate is not None:
            try:
                await self.validate(target)
            except ConfigValidationError:
                await self._restore(target, previous)
                raise

        if self.apply is not None:
            try:
                await self.apply()
            except ConfigApplyError:
                await self._restore(target, previous)
                with contextlib.suppress(ConfigApplyError):
                    await self.apply()  # best-effort: bring the service back up on the old config
                raise

        return hashlib.sha256(content.encode()).hexdigest()

    async def _write_atomic(self, target: Path, content: bytes) -> None:
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = target.parent / f".{target.name}.nasos-tmp"
        with tmp_path.open("wb") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp_path, self.mode)
        if self.owner is not None and self.group is not None:
            shutil.chown(tmp_path, user=self.owner, group=self.group)
        elif self.owner is not None:
            shutil.chown(tmp_path, user=self.owner)
        elif self.group is not None:
            shutil.chown(tmp_path, group=self.group)
        tmp_path.rename(target)  # same dir as target: atomic, SELinux labels inherit from the dir

        result = await self.runner.run(["restorecon", str(target)])
        if not result.ok:
            logger.warning("restorecon %s failed (non-fatal): %s", target, result.stderr.strip())

    async def _restore(self, target: Path, previous: bytes | None) -> None:
        if previous is None:
            target.unlink(missing_ok=True)
        else:
            await self._write_atomic(target, previous)
        logger.warning("rolled back %s after a failed validate/apply", target)

    def _backup(self, target: Path, previous: bytes) -> None:
        backup_dir = Path(self.backup_dir)
        backup_dir.mkdir(parents=True, exist_ok=True)
        stamp = time.strftime("%Y%m%dT%H%M%S")
        (backup_dir / f"{target.name}.{stamp}").write_bytes(previous)

        existing = sorted(backup_dir.glob(f"{target.name}.*"))
        for stale in existing[:-MAX_BACKUPS]:
            stale.unlink(missing_ok=True)
