"""Renders the systemd units Storage Manager owns (PLAN.md §6): a
`.mount` unit per volume, the `nasos-volumes.target` all of them attach to,
and `RequiresMountsFor=`/`After=` drop-ins for smb/nfs-server/vsftpd so
those services never start before their volumes are mounted.

Unit *names* come from `systemd-escape` (PLAN.md §6: "names via
systemd-escape -p --suffix=mount") rather than a hand-rolled escaping
algorithm, since that's the one tool guaranteed to match how systemd
itself would derive a `Where=` mountpoint's unit name.
"""

from __future__ import annotations

from nasos import __version__
from nasos.system.runner import Runner

VOLUMES_TARGET = "nasos-volumes.target"
VOLUMES_TARGET_UNIT_PATH = f"/etc/systemd/system/{VOLUMES_TARGET}"

# No timestamp, unlike system/managedfile.py's render_header — a unit file
# is golden-file tested (PLAN.md §12's M4 gate: "golden .mount/target/
# drop-ins") the same way services/samba_config.py's render_nasos_conf is,
# which needs its header to be deterministic across runs.
_HEADER = f"# Generated by NAS-OS {__version__}. DO NOT EDIT; managed by Storage Manager.\n"


class MountUnitError(Exception):
    pass


async def mount_unit_name(runner: Runner, mountpoint: str) -> str:
    result = await runner.run(["systemd-escape", "-p", "--suffix=mount", mountpoint])
    name = result.stdout.strip()
    if not result.ok or not name:
        # An empty name would otherwise get treated downstream as "no
        # filename" and silently write into the unit *directory* itself —
        # found via a live `make dev` walkthrough (a FakeRunner with no
        # matching expectation for this exact mountpoint returned empty
        # canned output), never let it through.
        raise MountUnitError(result.stderr.strip() or "systemd-escape produced no unit name")
    return name


def render_mount_unit(*, uuid: str, where: str, fstype: str) -> str:
    return (
        f"{_HEADER}"
        "[Unit]\n"
        f"Description=NAS-OS volume {where}\n"
        "\n"
        "[Mount]\n"
        f"What=UUID={uuid}\n"
        f"Where={where}\n"
        f"Type={fstype}\n"
        "Options=defaults,noatime\n"
        "\n"
        "[Install]\n"
        f"WantedBy={VOLUMES_TARGET}\n"
    )


def render_volumes_target() -> str:
    return (
        f"{_HEADER}"
        "[Unit]\n"
        "Description=NAS-OS managed volumes\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def render_service_dropin(*, mountpoints: list[str]) -> str:
    """`mountpoints` is every currently-managed volume's `Where=`, not just
    the one just created — smb/nfs-server/vsftpd each get one drop-in that
    always lists the full current set, regenerated on every volume
    create/remove (mirroring how nasos.conf is always the full re-rendered
    share list, not a per-share diff — PLAN.md §2's same pattern)."""
    requires = " ".join(mountpoints)
    return f"{_HEADER}[Unit]\nAfter={VOLUMES_TARGET}\nRequiresMountsFor={requires}\n"


def service_dropin_path(unit: str) -> str:
    return f"/etc/systemd/system/{unit}.d/50-nasos-volumes.conf"


def mount_unit_path(unit_name: str) -> str:
    return f"/etc/systemd/system/{unit_name}"
