"""Golden-file test for nasos.conf (PLAN.md M2 gate). The golden file was
generated from this exact input and independently verified against the
real `testparm` binary (extracted from the samba-common-tools RPM, no
Samba installed on the dev box) during M2 development — see the M2 report
for the full testparm dump this produced.
"""

from __future__ import annotations

from pathlib import Path

from nasos.db.models import Share, SharePermission
from nasos.services.samba_config import build_share_view, render_nasos_conf

GOLDEN_PATH = Path(__file__).parent.parent / "fixtures" / "golden" / "nasos.conf"


def test_render_nasos_conf_matches_golden_file() -> None:
    shares = [
        build_share_view(
            Share(name="media", path="/volume1/media", volume_id=1),
            [
                SharePermission(share_id=1, principal_type="user", principal="alice", level="rw"),
                SharePermission(share_id=1, principal_type="user", principal="bob", level="ro"),
                SharePermission(share_id=1, principal_type="group", principal="family", level="ro"),
            ],
        ),
        build_share_view(
            Share(name="backups", path="/volume1/backups", volume_id=1),
            [
                SharePermission(share_id=2, principal_type="user", principal="alice", level="rw"),
            ],
        ),
        build_share_view(
            Share(name="public", path="/volume1/public", volume_id=1),
            [],
        ),
    ]

    rendered = render_nasos_conf(shares)
    assert rendered == GOLDEN_PATH.read_text()


def test_build_share_view_orders_valid_users_before_splitting_rw_ro() -> None:
    view = build_share_view(
        Share(name="x", path="/volume1/x", volume_id=1),
        [
            SharePermission(share_id=1, principal_type="user", principal="alice", level="rw"),
            SharePermission(share_id=1, principal_type="group", principal="staff", level="ro"),
        ],
    )
    assert view.valid_users == ["alice", "@staff"]
    assert view.read_list == ["@staff"]
    assert view.write_list == ["alice"]


def test_share_with_no_permissions_omits_all_three_directives() -> None:
    view = build_share_view(Share(name="empty", path="/volume1/empty", volume_id=1), [])
    rendered = render_nasos_conf([view])
    assert "valid users" not in rendered
    assert "read list" not in rendered
    assert "write list" not in rendered


def test_no_shares_renders_just_the_header() -> None:
    rendered = render_nasos_conf([])
    assert rendered.startswith("# Generated by NAS-OS")
    assert "[" not in rendered
