"""nasos-setup: minimal M1 bootstrap.

Writes /etc/nasos/nasos.toml if missing and generates a self-signed TLS
cert. The full idempotent installer described in PLAN.md §10 (distro
package install, SELinux booleans/fcontext, first-admin creation, Samba,
firewalld, service enable) grows in over M2-M8 as the subsystems it
configures come online; this is a deliberately small placeholder until then.
"""

from __future__ import annotations

import argparse
import datetime as dt
import ipaddress
import socket
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import NameOID

from nasos.config import get_settings

DEFAULT_CONFIG = """\
# Generated by nasos-setup. Edit freely; NAS-OS only appends keys it
# doesn't find here, it never rewrites ones you've set.
mode = "prod"
"""


def _write_config(path: Path, *, force: bool) -> None:
    if path.exists() and not force:
        print(f"{path} already exists, leaving it alone")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(DEFAULT_CONFIG)
    print(f"wrote {path}")


def _ensure_cert(cert_path: Path, key_path: Path, *, hostname: str, force: bool) -> None:
    if cert_path.exists() and key_path.exists() and not force:
        print(f"{cert_path} already exists, leaving it alone")
        return
    cert_path.parent.mkdir(parents=True, exist_ok=True)

    key = ec.generate_private_key(ec.SECP256R1())
    subject = issuer = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, hostname)])
    san: list[x509.GeneralName] = [x509.DNSName(hostname), x509.DNSName("nasos.local")]
    try:
        san.append(x509.IPAddress(ipaddress.ip_address(socket.gethostbyname(hostname))))
    except (OSError, ValueError):
        pass

    now = dt.datetime.now(dt.UTC)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + dt.timedelta(days=3650))
        .add_extension(x509.SubjectAlternativeName(san), critical=False)
        .sign(key, hashes.SHA256())
    )

    key_path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    key_path.chmod(0o640)
    cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))
    print(f"wrote {cert_path} and {key_path} (self-signed EC P-256, 10y, CN={hostname})")


def main() -> None:
    parser = argparse.ArgumentParser(prog="nasos-setup")
    parser.add_argument("--non-interactive", action="store_true")
    parser.add_argument("--force", action="store_true", help="overwrite existing config/cert")
    args = parser.parse_args()

    settings = get_settings()
    hostname = settings.hostname_override or socket.gethostname()

    _write_config(Path(settings.config_file), force=args.force)
    _ensure_cert(
        Path(settings.tls_cert), Path(settings.tls_key), hostname=hostname, force=args.force
    )

    print(
        "Minimal M1 setup complete. Package installation, SELinux, first-admin "
        "creation, Samba and firewalld steps land in later milestones (PLAN.md §10)."
    )
    print(
        f"Once nasos-agent.socket and nasos.service are running: "
        f"https://{hostname}:{settings.https_port}"
    )


if __name__ == "__main__":
    main()
