"""Renders /etc/samba/nasos.conf from the shares/share_permissions tables
(PLAN.md §2's Samba row). Pure Jinja2 templating — no system calls; the
rendered text crosses the RPC boundary and the agent's ManagedFile does the
actual privileged write/validate/apply (agent/handlers/samba.py).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from nasos import __version__
from nasos.db.models import Share, SharePermission

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_env = Environment(
    loader=FileSystemLoader(_TEMPLATES_DIR),
    trim_blocks=True,
    lstrip_blocks=True,
    autoescape=select_autoescape(disabled_extensions=(".j2",), default=False),
)


@dataclass
class ShareSambaView:
    """What the template needs for one share — already resolved from
    Share/SharePermission rows, so the template itself stays dumb.
    """

    name: str
    path: str
    valid_users: list[str]
    read_list: list[str]
    write_list: list[str]


def _principal_ref(kind: str, name: str) -> str:
    return f"@{name}" if kind == "group" else name


def build_share_view(share: Share, permissions: list[SharePermission]) -> ShareSambaView:
    valid_users = [_principal_ref(p.principal_type, p.principal) for p in permissions]
    read_list = [
        _principal_ref(p.principal_type, p.principal) for p in permissions if p.level == "ro"
    ]
    write_list = [
        _principal_ref(p.principal_type, p.principal) for p in permissions if p.level == "rw"
    ]
    return ShareSambaView(
        name=share.name,
        path=share.path,
        valid_users=valid_users,
        read_list=read_list,
        write_list=write_list,
    )


def render_nasos_conf(shares: list[ShareSambaView]) -> str:
    template = _env.get_template("samba_nasos_conf.j2")
    header = (
        f"# Generated by NAS-OS {__version__}. DO NOT EDIT; "
        "manage shares from Control Panel -> Shared Folders.\n"
    )
    return template.render(header=header, shares=shares)
