#Type Path                 Mode UID   GID   Age Argument
d     /run/nasos           0755 root  root  -
d     /run/nasos/workers   0750 root  nasos -
d     /var/lib/nasos       0750 nasos nasos -
d     /var/log/nasos       0750 nasos nasos -
